### ISSUE TITLE
Deeplinking to /#/route

### ISSUE THREAD

**Issue by nukeador** [opentripplanner/otp-react-redux#1167]
Hi,

I would like to deeplink the list all routes from a link on a external site but accessing to mysite.com/#/route is not loading the component, only the main page is loaded.

Is there a way I can handle this? I tried to further config nginx but the result is the same.

```
location / {
                try_files $uri /index.html;
}
```

**Comment by nukeador** [comment]
I've noticed that other URL such as /#/nearby do work just fine for deeplinking

**Comment by nukeador** [comment]
It seems you should fix for `TypeError: payload is null` in [setViewedStop](https://github.com/opentripplanner/otp-react-redux/blob/97f36fd66f0d4e89a31163d2e134c15fa89d38ea/lib/actions/ui.js#L185)

This issue is related to the `setViewedStop` function in `ui.js`, where a `TypeError` is thrown when `payload` is `null`. This error occurs when attempting to access properties of `payload` without first checking if `payload` is not `null`.

**Original Code:**

```javascript
export function setViewedStop(payload, viewer = 'nearby') {
  return function (dispatch, getState) {
    // payload.stopId may be undefined, which is ok as will be ignored by getPathFromParts
    if (viewer === 'nearby') {
      if (payload.lat && payload.lon) {
        dispatch(setViewedNearbyCoords(payload))
       } else {
        dispatch(fetchNearbyFromStopId(payload.stopId))
      }
    } else {
      dispatch(viewStop(payload))
      const path = getPathFromParts('schedule', payload.stopId)
       if (payload) dispatch(routeTo(path))
    }
  }
}
```

**Problem:**

The function `setViewedStop` does not handle the case where `payload` is `null`. This can lead to a `TypeError` when trying to access `payload.lat`, `payload.lon`, or `payload.stopId`.

**Solution:**

Add a check at the beginning of the function to ensure that `payload` is not `null` before attempting to access its properties. If `payload` is `null`, the function should return early to prevent the error.

**Updated Code:**

```javascript
export function setViewedStop(payload, viewer = 'nearby') {
  return function (dispatch, getState) {
    if (!payload) {
      // Handle the case where payload is null or undefined
      // You might want to dispatch an action to set a default state or show an error
      return;
    }
    // payload.stopId may be undefined, which is ok as will be ignored by getPathFromParts
    if (viewer === 'nearby') {
      if (payload.lat && payload.lon) {
        dispatch(setViewedNearbyCoords(payload))
      } else {
        dispatch(fetchNearbyFromStopId(payload.stopId))
      }
    } else {
      dispatch(viewStop(payload))
      const path = getPathFromParts('schedule', payload.stopId)
      if (payload) dispatch(routeTo(path))
    }
  }
}
```

**Comment by miles-grant-ibigroup** [comment]
Thanks so much for your detailed bug report! Made opening this PR really easy. Appreciate your help and thanks again for contributing!
