### ISSUE TITLE
Route viewer does not display if route_long_name is not populated

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#121]
The exceptions below are produced when trying to open the route viewer from the trip planning view.
No routes are displayed as a result and the entire screen becomes blank.

![image](https://user-images.githubusercontent.com/56846598/73023410-78bc9f80-3df9-11ea-9805-6c882ee8fb7b.png)

Fragment where the exception occurs: `d=n.longName.split(c)`

**Comment by landonreed** [comment]
Fixed by #116.
