### ISSUE TITLE
Replace mastarm with webpack

### ISSUE THREAD

**Issue by mpaine-act** [opentripplanner/otp-react-redux#221]
Would the OTP team support a pull request to replace mastarm with webpack?  Webpack is the standard and mastarm is implemented by Conveyal, which appears it's main feature to support AWS which doesn't apply to some OTP installations.   Also, webpack is more universal and easier to customize.   Perhaps mastarm2 could become a decorator around webpack to preserve the AWS features.

**Comment by binh-dam-ibigroup** [comment]
Closing this issue, it was fixed by #447.
