### ISSUE TITLE
OTP Geocoder support

### ISSUE THREAD

**Issue by stemove** [opentripplanner/otp-react-redux#271]
hi... 

is supported default OTP geocoding API in types of geoder engine instead of PELIAS, ARCGIS?
https://github.com/opentripplanner/otp-react-redux/blob/dev/example-config.yml#L77

**Comment by landonreed** [comment]
Hello @stemove. No, the default OTP geocoding is not supported. PELIAS and ARCGIS are the only integrations with geocoder services supported right now.
