### ISSUE TITLE
Stop viewer in schedule mode only shows the first 3 trips for a day.

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#287]
## Observed behavior

The stop viewer in **Schedule View** only shows the first 3 departures of the selected day sorted by time starting at midnight on each route/pattern that serves a particular stop.

On some routes, post-midnight departure times are shown as first departures, to the top of the schedule, rather than towards the bottom with the last departures of the day.

## TBD Expected behavior

The stop viewer should show either all departures for the day or a limited number of departures starting from around the time indicated in the query and date selected in the stop viewer.

Furthermore, the departure times should be sorted to show times from the beginning of service to the end of service for the selected day in Stop Viewer. For instance, a bus running at a 20-minute frequency from 06:00 to 01:00 at night should display a portion of this sequence: 06:00, 06:20, ... , 23:40, 00:00, 00:20, 00:40, 01:00.

## Steps to reproduce

Go to https://beta-plan.septa.org/#/stop/SEPTA%20Bus:101 and toggle the Schedule Mode on the Stop Viewer.

Example 1 - Only first departures of the day are shown regardless of time of day:
- Observe the departures shown for route 29 (see screenshot below).
- Compare with the published timetable http://septa.org/schedules/bus/pdf/029.pdf (or GTFS equivalent).
- The departures shown are for the first 3 trips in the morning.

The screenshot below was taken at 6pm local time.
![image](https://user-images.githubusercontent.com/56846598/101845317-5d937500-3b1c-11eb-98c0-9767a5d841d5.png)

Example 2 - Incorrect departure order
- Observe the departures shown for route 64 with terminus at 49th (see screenshot below).
- Compare with the published timetable http://septa.org/schedules/bus/pdf/064.pdf (or GTFS equivalent).
- The first departure listed is the 00:14 (12:14 am), which is the last trip of the day.

![image](https://user-images.githubusercontent.com/56846598/101845287-4f455900-3b1c-11eb-9f9f-4d62974f632e.png)

**Comment by fpurcell** [comment]
Bug in ear:  this would be a useful component in OTP-UI

BTW, would probably also want BLOCK column to be optionally show (if not already optional).

**Comment by binh-dam-ibigroup** [comment]
> Bug in ear: this would be a useful component in OTP-UI
> 
> BTW, would probably also want BLOCK column to be optionally show (if not already optional).

Whether the block column is shown is configurable in https://github.com/opentripplanner/otp-react-redux/pull/292/commits/1c08e0c10a453905bcfcbe1a04763d1828b16506.
