### ISSUE TITLE
Calltaker/Field Trip: buttons off-view in Firefox

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#330]
Buttons for Calltaker/Field Trip appear off view in Firefox. The main call taker button appears on the right edge of the browser window.

![image](https://user-images.githubusercontent.com/56846598/108088481-81a49280-7046-11eb-9adc-a8b7955cbe7c.png)

**Comment by landonreed** [comment]
Thanks for logging this one, @binh-dam-ibigroup.

**Comment by landonreed** [comment]
Looks like we just need to render these within a div with `position: relative`. I'll add a commit to #230.
