### ISSUE TITLE
Stop ID Mismatch

### ISSUE THREAD

**Issue by miles-grant-ibigroup** [opentripplanner/otp-react-redux#411]
As seen below: the Community Transit GTFS feed is reporting different stop IDs than are shown in the interface.

<img width="471" alt="Screen Shot 2021-07-09 at 12 21 55 PM" src="https://user-images.githubusercontent.com/86619099/125110263-59c7d100-e0b2-11eb-95ab-485e15e4140f.png">

**Comment by binh-dam-ibigroup** [comment]
Was fixed by #564.
