### ISSUE TITLE
UI freezes on OTP request timeout

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#413]
On deployments that use OTP Middleware, performing an itinerary search such as [this one](https://atl-rides.ibi-transit.com/#/?ui_activeSearch=wbvqz4syz&ui_activeItinerary=0&fromPlace=Ponce%20City%20Market%2C%20Atlanta%2C%20GA%2C%20USA%3A%3A33.772553%2C-84.36539&toPlace=Westview%20Cemetery%2C%20Atlanta%2C%20GA%2C%20USA%3A%3A33.746832%2C-84.449352&date=2021-07-12&time=10%3A00&arriveBy=false&mode=WALK%2CBUS%2CSUBWAY%2CTRAM&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=true&companies=&bannedRoutes=&numItineraries=3&otherThanPreferredRoutesPenalty=900&preferredRoutes=) causes a UI freeze after some itinerary results are initially displayed. The server (OTP-middleware) logs show a timeout issue, and returns a 500 error to the UI. The UI or the backend should handle such situations gracefully instead of freezing.

**Comment by landonreed** [comment]
I believe this was resolved within @evansiroky's #230.
