### ISSUE TITLE
New stop viewer issues/improvements

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#483]
Issues arising from enhanced stop viewer features (bugs introduced by #469 and maybe #423)
- The map marker (a teal dot on the map) that identifies the selected stop in the stop viewer has been lost.
- Nearby micromobility devices are shown at all zoom levels (even when zoomed far and the micromobility map layers are turned off). They should be shown at the same zoom levels as the enhanced stop bubbles.

**Comment by miles-grant-ibigroup** [comment]
Via https://github.com/opentripplanner/otp-react-redux/pull/469#issuecomment-955100324: 

>  the map should auto zoom into a stop to the level where you can see the stop viewer bubbles when you click on "Stop Viewer"

**Comment by miles-grant-ibigroup** [comment]
Via https://github.com/opentripplanner/otp-react-redux/pull/469#discussion_r738465518:

>  there should be a highlight effect on the stop viewer as you hover the related stops too.

**Comment by miles-grant-ibigroup** [comment]
> The map marker (a teal dot on the map) that identifies the selected stop in the stop viewer has been lost.

This has been addressed in #492 via zooming into the stop when opening the stop viewer
