### ISSUE TITLE
Saved Trips system does not indicate when it is loading, allows duplicate button presses

### ISSUE THREAD

**Issue by daniel-heppner-ibigroup** [opentripplanner/otp-react-redux#488]
On the following pages there is no indication that something is happening after you press a button:
- /account/trips/new, after clicking on "Save Preferences". As a result, you're able to save multiple trips with the same name. (should be a server-side check for this)
- /account/trips, clicking on "Pause" or "Delete"
- /account/trips/:id, clicking on any button that causes a server request

When a request is in action, buttons should disable to prevent another request from being sent and something should indicate to the user that an action is in progress.

**Comment by binh-dam-ibigroup** [comment]
This was closed by #750.
