### ISSUE TITLE
OTP-RR Rendering Straight Lines Instead of Following Streets

### ISSUE THREAD

**Issue by darmentrout** [opentripplanner/otp-react-redux#501]
My instance of OTP-RR renders some trip legs as straight lines that cross over roads and buildings. I have tested with OTP 1.4.0, OTP 1.5.0, and the IBI Transit fork of OTP (1.5.0). I get the same results each time. As shown in [this example trip](http://ride.cota.com/#/?ui_activeSearch=dr86ufkg5&ui_activeItinerary=0&fromPlace=E%205TH%20AVE%20%26%20ALTON%20AVE%20%28Central%20Ohio%20Transit%20Authority%20Stop%20ID%201648%29%2C%20Columbus%2C%20OH%2C%20USA%3A%3A39.984885%2C-82.926497&toPlace=INTERNATIONAL%20GATEWAY%20%26%20SAWYER%20RD%20%28Central%20Ohio%20Transit%20Authority%20Stop%20ID%205382%29%2C%20Columbus%2C%20OH%2C%20USA%3A%3A39.998717%2C-82.892309&date=2021-11-16&time=11%3A54&arriveBy=false&mode=WALK%2CBUS&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=false&companies=&bannedRoutes=&numItineraries=3&otherThanPreferredRoutesPenalty=900&preferredRoutes=), the path of the bus is shown crossing the runway of our regional airport. The bus line follows the street correctly when planning the same trip in the default OTP interface. This is very similar to what was reported in issue #119.

**Comment by miles-grant-ibigroup** [comment]
This should be fixed with https://github.com/opentripplanner/otp-ui/pull/300 (commit https://github.com/opentripplanner/otp-ui/pull/300/commits/d4e9d7f78c55cbaf4e2dd854371574ce8c19de32)

This update has unfortunately not yet made it to OTP-RR, but I will update this ticket when it does.

**Comment by miles-grant-ibigroup** [comment]
The fix is published at https://github.com/opentripplanner/otp-ui/releases/tag/%40opentripplanner%2Fcore-utils-v4.5.0-alpha.1. You may be able to get this fixed if you force-upgrade your core-utils version.

**Comment by miles-grant-ibigroup** [comment]
Happy to report the fixed behavior is now in the dev branch (no package overrides needed). Let me know if it works for you!

**Comment by darmentrout** [comment]
I appreciate your help! 

I updated core-utils but our trip planner now only shows a white screen. This is the error in the console:
`RangeError: Format string contains an unescaped latin alphabet character `A``

This is an example warning from the build process:
```
WARNING in ./node_modules/@opentripplanner/core-utils/esm/types.js 460:27-53
export 'ReactPropTypeLocationNames' (imported as 'ReactPropTypeLocationNames') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)
 @ ./node_modules/@opentripplanner/core-utils/esm/index.js 10:0-33 22:9-14
 @ ./lib/components/form/settings-preview.js 12:0-52 40:20-53
 @ ./lib/index.js 7:0-65 44:0-54:13
 @ ./example.js 26:0-125 56:7-23 57:8-25 78:42-52 84:89-105 91:42-45 97:73-83 100:46-49 107:46-62
```

We have use a modified version of the otp-rr front-end so I don't think I can switch to the dev branch (or any branch). Would it be possible to swap in a file or two from the recently updated version?

**Comment by miles-grant-ibigroup** [comment]
Uh-oh! Yeah I think that error is likely due to core-utils changes being out of sync with otp-rr changes. I would try to merge in the dev branch if possible, but if it's not possible then my approach to this issue would be to selectively replace merge otp-rr files that are appearing in the stack trace and continue to do so until the errors go away. 

Another option would be to fork core-utils at the version that worked for you and then manually add the `legGeometry` patch (https://github.com/opentripplanner/otp-ui/pull/300/commits/d4e9d7f78c55cbaf4e2dd854371574ce8c19de32)

Good luck and please do update us as to how the patch works for you!

**Comment by darmentrout** [comment]
Thanks for the suggestions. I tried modifying map.js, I even completely replaced it with the new version at one point, but it still draws straight lines. When I update core-utils, the stack trace in the browser points only to main.js which isn't very helpful. I'll keep at it!

**Comment by miles-grant-ibigroup** [comment]
That's really annoying! The only thing I can think of to look out for is to make sure there is no `interStopGeometry` in the leg, as this will override the `legGeometry`.

**Comment by darmentrout** [comment]
It works now! Here's how it went down for any future readers. 

First I resolved the "latin A" error by installing **core-utils@3.2.4**. This is the last version before the changeover to version 4 (which uses a different date formatting method and is thus incompatible with our custom instance of OTP-RR). 

Next, I modified **map.js** so that function `itineraryToTransitive` matches the updates made in commit opentripplanner/otp-ui@d4e9d7f. There are three map.js files, one each in the _src_, _lib_, and _esm_ folders. The latter seems to be the only one that makes a difference on the front-end. 

I also made sure that my nodejs was up to date. Version 4 of core-utils requires at least v13. This didn't really have a direct bearing on the solution above but I think it's easy to overlook and so worth noting. It helped while doing trial-and-error to determine which version of core-utils to go with. 

This [curvy example trip](http://ride.cota.com/#/?ui_activeSearch=4hdnvsy43&ui_activeItinerary=0&fromPlace=N%20HAMILTON%20RD%20%26%20E%205TH%20AVE%20%28Central%20Ohio%20Transit%20Authority%20Stop%20ID%205727%29%2C%20Columbus%2C%20OH%2C%20USA%3A%3A39.989803%2C-82.868796&toPlace=JOHN%20GLENN%20INTERNATIONAL%20%20AIRPORT%20BAGGAGE%20CLAIM%20%28Central%20Ohio%20Transit%20Authority%20Stop%20ID%205383%29%2C%20Columbus%2C%20OH%2C%20USA%3A%3A39.998638%2C-82.885054&date=2021-11-18&time=10%3A28&arriveBy=false&mode=WALK%2CBUS&showIntermediateStops=true&maxWalkDistance=1207&optimize=QUICK&walkSpeed=1.34&ignoreRealtimeUpdates=false&companies=&bannedRoutes=&numItineraries=3&otherThanPreferredRoutesPenalty=900&preferredRoutes=
) shows that the line follows the street rather than cutting across the runway as it did before. 

Thanks again for your help @miles-grant-ibigroup!

**Comment by binh-dam-ibigroup** [comment]
Closing this ticket because it has been resolved with the author.
