### ISSUE TITLE
Map rendering errors out randomly.

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#543]
I'm getting some errors while making a new account running FDOT. Are these related to this PR? There are a few errors so I'll just put the steps to recreate.
On this URL: http://localhost:9966/#/account/create/terms after creating an account and verifying email.
![image](https://user-images.githubusercontent.com/92878779/152869769-2e64fae2-9b29-4518-970b-835c03c3581b.png)
If this is not due to this PR, I won't block the PR with it. 
EDIT: this is not related to this PR

_Originally posted by @daniel-heppner-ibigroup in https://github.com/opentripplanner/otp-react-redux/issues/329#issuecomment-1031914559_

**Comment by miles-grant-ibigroup** [comment]
Is this possibly related to https://github.com/opentripplanner/otp-react-redux/issues/457?
