### ISSUE TITLE
Optimize for Fewest Transfers no longer working with OTP2

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#594]
The query param option to "Optimize for Fewest Transfers" (`optimize=TRANSFERS`) was removed from OTP 2 with commit  https://github.com/ibi-group/OpenTripPlanner/commit/61a2234e7976a9984bcf4866d1c3a2c1ba2ccd18, and searches from the UI that use that query parameter and value will fail with various error messages returned.

As a result, the OTP-RR UI should no longer use/pass this parameter when calling an OTP 2 `/plan` endpoint.

**Comment by miles-grant-ibigroup** [comment]
Was `optimize` and `optimizeBike` removed or just one of these two?
