### ISSUE TITLE
Wrong translation license?

### ISSUE THREAD

**Issue by comradekingu** [opentripplanner/otp-react-redux#669]
[OTP-UI Location Field](https://hosted.weblate.org/projects/otp-react-redux/otp-ui-location-field/) and
[OTP-UI Printable Itinerary](https://hosted.weblate.org/projects/otp-react-redux/otp-ui-printable-itinerary/)
say "proprietary".
I am not a fan of MIT, but that seems to be in error?

It runs afoul of the libre offering in https://hosted.weblate.org/hosting/
and can be changed in
https://hosted.weblate.org/settings/otp-react-redux/otp-ui-location-field/
and
https://hosted.weblate.org/settings/otp-react-redux/otp-ui-printable-itinerary/

**Comment by binh-dam-ibigroup** [comment]
Hi, thanks for your interest. We are still setting up weblate and getting a feel for it, so some things or settings may be missing. We will post an update when we are ready for contributions from the community!

**Comment by binh-dam-ibigroup** [comment]
@comradekingu Did you have a license for the translations other than MIT in mind?

**Comment by comradekingu** [comment]
ISC maybe. MIT is harder to get away from.

**Comment by comradekingu** [comment]
Seems good, but I can't look at the settings unless you add "kingu".

**Comment by binh-dam-ibigroup** [comment]
> Seems good, but I can't look at the settings unless you add "kingu".

Done @comradekingu

**Comment by comradekingu** [comment]
https://hosted.weblate.org/guide/otp-react-redux/otp-rr-main-ui/%20 shows an error
https://hosted.weblate.org/projects/otp-react-redux/otp-rr-main-ui/#alerts%20 says the secondary rate-limit is exceeded

The components differ between "Git" and "GitHub pull request" for VCS.

**Comment by binh-dam-ibigroup** [comment]
> https://hosted.weblate.org/guide/otp-react-redux/otp-rr-main-ui/ shows an error (The plugins suggested at the bottom there ensures all components are available for any added language, and the other one cleans up unused keys/strings) https://hosted.weblate.org/projects/otp-react-redux/otp-rr-main-ui/#alerts says the secondary rate-limit is exceeded
> 
> The components differ between "Git" and "GitHub pull request" for VCS.

Thanks @comradekingu for taking a look. What items you mentioned are blocking as opposed to are nice-to-have? I installed the two plugins to meet the community checklist, does anything need to change there? What setting could have caused the alert over the rate limit?

**Comment by binh-dam-ibigroup** [comment]
@comradekingu I changed all VCS settings to "GitHub Pull Request", which I thought I did initially, so thanks a lot for double-checking that!

**Comment by comradekingu** [comment]
https://hosted.weblate.org/projects/otp-react-redux/otp-ui-trip-form/ is missing webhooks.
https://docs.weblate.org/en/latest/admin/continuous.html#github-setup

Changing OTP-RR Main UI to point to `weblate://otp-react-redux/otp-ui-trip-form` I think will fix it.
It is the only other non-linked component.
If not, maybe deleting it and adding it again will fix it. Never seen that "secondary rate-limit" error before, so not quite sure what that is.

**Comment by binh-dam-ibigroup** [comment]
Hi @comradekingu, thanks so much for your assistance setting up OTP-react-redux on Hosted Weblate!

Before I close this issue, the last follow up item from the hosting approval email is the mention of Weblate in our READMEs. I have filed #677 and https://github.com/opentripplanner/otp-ui/pull/465 to that effect.
