### ISSUE TITLE
Mobile view: map is not fitting on route shape when selecting a route in route viewer.

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#703]
Steps to reproduce:
1. Open the route viewer in mobile view
2. Select a route
3. Observe that the shape of the route may be drawn, but the map does not reframe/recenter to fit the route shape.

**Comment by binh-dam-ibigroup** [comment]
This issue also occurs on desktop mode with a small/narrow browser window.

**Comment by miles-grant-ibigroup** [comment]
Possibly related: https://github.com/mapbox/mapbox-gl-js/issues/4344
