### ISSUE TITLE
Support Photon geocoder

### ISSUE THREAD

**Issue by amenk** [opentripplanner/otp-react-redux#706]
We would like to add support for the [Photon geocoder](https://photon.komoot.io/).

One advantage is that there is a free-to-use public instance of it provided by Komoot.
It seems to support forward and reverse geocoding, similar to Pelias.

[Comparison between both](https://github.com/pelias/pelias/issues/92).
 
Any comments are appreciated :-)

**Comment by amenk** [comment]
Just realized that the geocoding is provided by otp-ui https://github.com/opentripplanner/otp-ui/tree/master/packages/geocoder - not sure if this issue can be moved or I just close and reopen there?

**Comment by miles-grant-ibigroup** [comment]
This looks incredible! Your OTP-UI PR looks great! I'll go ahead and review that while closing this.

**Comment by amenk** [comment]
@miles-grant-ibigroup can we upgrade to geocoder 1.3.3 here in this project? shall I make a pull-request or is there some bot for this ?

```
    "@opentripplanner/geocoder": "^1.3.3",
```

In package.json and `yarn install` seems to be enough?
