### ISSUE TITLE
Show walking distance in meters, not miles

### ISSUE THREAD

**Issue by amenk** [opentripplanner/otp-react-redux#716]
I could not find a configuration option to display the walking distances in meters / kilometers instead of miles.

Is that possible already?

**Comment by miles-grant-ibigroup** [comment]
I believe setting the react-intl settings for distance should cause the formatting to change. @binh-dam-ibigroup may have more information

**Comment by binh-dam-ibigroup** [comment]
> I believe setting the react-intl settings for distance should cause the formatting to change. @binh-dam-ibigroup may have more information

react-intl can determine how to display a number and unit for a given locale, however OTP-RR is still yet to compute metric quantities.

**Comment by amenk** [comment]
So this would be a feature request then? Or is is already configurable in OTP-RR?

**Comment by binh-dam-ibigroup** [comment]
> So this would be a feature request then? Or is is already configurable in OTP-RR?

That would be a feature request.

**Comment by binh-dam-ibigroup** [comment]
@amenk So that you know, this is not an immediate priority for IBI, however we welcome pull requests.

**Comment by amenk** [comment]
I found out that [the basic rendering logic is already there](https://github.com/opentripplanner/otp-ui/blob/d0994b22e760de1ef329322cfe841f45e3e82db7/packages/humanize-distance/src/index.ts#L33
).

So it might be enough to set the second parameter [here](https://github.com/opentripplanner/otp-ui/blob/d0994b22e760de1ef329322cfe841f45e3e82db7/packages/itinerary-body/src/defaults/access-leg-description.tsx#L102
) to `true` / a configurable value.

    humanizeDistanceString(leg.distance, false, intl)

We also have to think about whether we let the end-user chose the unit or it's a system default configuration for the `config.yml` (or both)

PS: I am still wondering if there is a better workflow to contribute to OTP-UI than [this one](https://stackoverflow.com/a/74509073/288568).

**Comment by miles-grant-ibigroup** [comment]
Sorry for the delay on getting back to you -- well spotted on the metric support! I think it should somehow be set via the react-intl language. Let me know if you have any ideas there, or feel free to open a PR as a proposal and we can discuss further that way!

As for the workflow, I'm impressed you got `yarn link` working... For the most part my workflow is just a lot of copying files around :(

**Comment by amenk** [comment]
Setting that value to true works in the otp-ui storybook very well :-)

Unfortunately my `yarn link` approach does not seem to work that well in the moment, as I am getting
```
Error
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
Call Stack
 resolveDispatcher
  otp-ui/node_modules/react/cjs/react.development.js:1476:13
 useDebugValue
  otp-ui/node_modules/react/cjs/react.development.js:1540:22
 eval
  otp-ui/node_modules/styled-components/dist/styled-components.browser.esm.js:28:18500
 O
  otp-ui/node_modules/styled-components/dist/styled-components.browser.esm.js:28:19607
 renderWithHooks
  node_modules/react-dom/cjs/react-dom.development.js:14803:18
 updateForwardRef
  node_modules/react-dom/cjs/react-dom.development.js:16816:20
 beginWork
  node_modules/react-dom/cjs/react-dom.development.js:18645:16
 HTMLUnknownElement.callCallback
  node_modules/react-dom/cjs/react-dom.development.js:188:14
 Object.invokeGuardedCallbackDev
  node_modules/react-dom/cjs/react-dom.development.js:237:16
 invokeGuardedCallback
  node_modules/react-dom/cjs/react-dom.development.js:292:31
× Close
```

When trying this in the otp-react-redux application..

**Comment by miles-grant-ibigroup** [comment]
Yep this is a known issue! This is what I was wondering if you'd been able to solve. We don't use `yarn link` for this reason. Instead, either copying files into `node_modules` yourself or setting the package.json version to be a path to the local otp-ui package is sadly the way to go...

**Comment by amenk** [comment]
@miles-grant-ibigroup let's continue this discussion in #773

**Comment by amenk** [comment]
This is actually a duplicate of

https://github.com/opentripplanner/otp-react-redux/issues/158
https://github.com/opentripplanner/otp-ui/issues/116

So I am closing this one here.
