### ISSUE TITLE
Do not use Google Fonts CDN?

### ISSUE THREAD

**Issue by amenk** [opentripplanner/otp-react-redux#725]
Usage of Google fonts can be problematic in EU, especially if there is no cookie consent banner.

Shall we replace [the usage of Google font CDN](https://github.com/opentripplanner/otp-react-redux/blob/0821fe14fd3abb515b626044703c124003f67dc7/lib/index.tpl.html#L14) with either 

1. a local copy or 
2. a drop-in replacement like https://fonts.bunny.net/ ?

**Comment by miles-grant-ibigroup** [comment]
We're actively moving to use the system font stack!

**Comment by amenk** [comment]
Great :-)

**Comment by miles-grant-ibigroup** [comment]
Thanks for mentioning that bunny.net website though! Looks very cool will keep it in mind for the future.
