### ISSUE TITLE
Some actions are not properly initialized

### ISSUE THREAD

**Issue by otrichet** [opentripplanner/otp-react-redux#740]
With local storage persistence enabled:
```yaml
persistence:
  enabled: true
  strategy: localStorage
```

clicking on `yes` to the question `Remember recent searches/places?` generates the following error:

![error-enable-tracking](https://user-images.githubusercontent.com/7985870/209994891-865ad000-f312-4efa-9391-d3adfdeb3319.png)

This is due to import cycles in the code. One example of these is `components/form/user-settings.js -> actions/api.js -> util/state.js -> components/form/user-settings.js`.
After breaking some of these cycles, the code works again as expected.

I created a test branch (https://github.com/otrichet/otp-react-redux/commits/import-cyles) to
- add a plugin that detects these cycles at build time (commit https://github.com/otrichet/otp-react-redux/commit/adcd23a6c7f0ac0e7f786a6c15153032d2b253a6)
- break some of these cycles to confirm it solves this issue (commits https://github.com/otrichet/otp-react-redux/commit/2f97dcec22e14d841404cc9fe16b6567207826bd and https://github.com/otrichet/otp-react-redux/commit/8fe2d4d0e3e6250ff28e6f07ee763d1800840377)

**Comment by miles-grant-ibigroup** [comment]
Thanks for reporting this and even greater thanks for finding a solution! I would merge your branch right away (it's great!) except that it's about to have a lot of conflicts with similar work we're doing. I can go ahead and recreate your work once that conflicting PR is merged.

Thanks again for reporting! Much appreciated.

**Comment by otrichet** [comment]
I only wanted to start a discussion on this issue and did not expect such a quick response.
Thanks for incorporating these changes.

Please note that there are still import cycles. This is the reason for the `const existingCycles = 10` in the configuration, it's a attempt to avoid adding more cycles than those existing.

**Comment by miles-grant-ibigroup** [comment]
Thanks for bringing changes to incorporate! I saw that -- I think that's a fine solution for now. I might add an issue to focus on removing the remaining cycles, those are never good.
