### ISSUE TITLE
Node version to run the example

### ISSUE THREAD

**Issue by Rafouf69** [opentripplanner/otp-react-redux#802]
Should not we specify which NodeJs version we shall use to run the example? 

Since by using the NodeJs v19.7.0 on Ubuntu 22.04.2 I get this [error](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported).  
[Note](https://stackoverflow.com/a/73027407) that by downgrading the Node version, we open some security problem.

**Comment by miles-grant-ibigroup** [comment]
We now specify what node version should be used in in our package.json
