### ISSUE TITLE
Date/old settings picker styles broken

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [opentripplanner/otp-react-redux#919]
#911 broke the CSS for the date time selector and the trip settings. The commit before #911 was merged does not show the defect. Note that the broken date time selection styling also appears in #700 at time of writing.

<img width="408" alt="image" src="https://github.com/opentripplanner/otp-react-redux/assets/56846598/dc639e3c-d03f-4697-afd3-7e3b0c04aca6">

**Comment by miles-grant-ibigroup** [comment]
@amy-corson-ibigroup I think we're good to close this now with the latest trip form updates
